# Generated by Django 4.2.19 on 2025-04-16 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='level',
            field=models.CharField(choices=[('nursery', 'Nursery'), ('primary', 'Primary')], default='null', max_length=20),
            preserve_default=False,
        ),
    ]
