# Generated by Django 4.2.19 on 2025-04-16 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='graded',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='term',
            name='term_type',
            field=models.CharField(default='none', max_length=250),
            preserve_default=False,
        ),
    ]
