# Generated by Django 4.2.19 on 2025-04-16 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassName',
            fields=[
                ('class_id', models.AutoField(primary_key=True, serialize=False)),
                ('class_name', models.CharField(max_length=250)),
            ],
            options={
                'db_table': 'Class',
                'managed': True,
            },
        ),
    ]
